site_name: Horde Wiki
copyright: Copyright &copy; 2021 Illia Novak
site_author: anakilivo
repo_url: https://github.com/anakilivo/wiki
repo_name: anakilivo/wiki
plugins:
  - search:
      min_search_length: 3
      lang:
        - en
        - ru
  - i18n:
      default_language: en
      languages:
        en: english
        ru: русский
theme:
  name: material
  palette:
    scheme: slate
    primary: red
  logo: assets/horde.png
  favicon: assets/horde.png
  icon:
    repo: fontawesome/brands/github-square
extra:
  version: 0.0.1
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/anakilivo
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/illia-novak/
    - icon: fontawesome/solid/paper-plane
      link: mailto:anakilivo@gmail.com
markdown_extensions:
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.superfences
  - def_list
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js